---
- name: Test Playbook
  become: true
  hosts: aws_srv1

  tasks:

  - name: Test Debug
    shell: curl http://169.254.169.254/latest/meta-data/public-ipv4
    register: server_ipv4

  - name: Print IPv4
    debug: 
      msg: "IPv4 of Server: {{ server_ipv4.stdout }}"