#!/bin/bash
sudo apt update -y && sudo apt install nginx -y

public_ipv4=`curl http://169.254.169.254/latest/meta-data/public-ipv4`

sudo -s

rm /var/www/html/*
cat <<EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p>The public IPv4 address will be displayed next <a href="http://">$public_ipv4</a></br>
Generated by Terraform
</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
EOF

chmod 755 -R /var/www/html/

nginx -s reload
systemctl enable nginx
systemctl start nginx