version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=""
    networks:
      - app-network

  database:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
      - MYSQL_DATABASE=forge
    networks:
      - app-network

  voting:
    build:
      context: .
    image: voting:latest
    container_name: voting
    ports:
      - 9000:9000
    env_file:
      - .env.dist
    depends_on:
      - database
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "20000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - voting
    networks:
      - app-network

networks:
  app-network:
