---
# tasks file for inodejs_npm
- name: Check if Node.js is installed
  ansible.builtin.command: node --version
  register: nodejs_version
  ignore_errors: true
  changed_when: nodejs_version.rc == 127 or nodejs_version != 0

- name: Install nodejs
  when: nodejs_version.rc == 127 or nodejs_version.rc != 0
  block:

    - name: Make Dir for Downloads
      ansible.builtin.file:
        path: /home/ubuntu/downloads
        state: directory
        mode: '0755'

    - name: Download Node.js binary
      ansible.builtin.get_url:
        url: "https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
        dest: "{{ download_folder }}/node-v18.17.1-linux-x64.tar.xz"
        mode: '0755'

    - name: Extract Node.js binary
      ansible.builtin.unarchive:
        src: "{{ download_folder }}/node-v18.17.1-linux-x64.tar.xz"
        dest: "{{ download_folder }}/"
        owner: ubuntu
        mode: '0777'
        remote_src: true

    - name: Add Node.js to PATH
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH=$PATH:/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin'
        create: true
        mode: '0755'

    - name: Create symlink to Node.js binary
      ansible.builtin.file:
        src: "/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin/node"
        dest: "/usr/sbin/node"
        state: link

    - name: Create symlink to npm binary
      ansible.builtin.file:
        src: "/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin/npm"
        dest: "/usr/sbin/npm"
        state: link
