FROM ruby:3.2.0

# Установка зависимостей для Node.js и Yarn
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get update -qq \
    && apt-get install -y nodejs

# Установка yarn
RUN npm install -g yarn

# Установка дополнительных зависимостей, как указано в конфигурации
RUN apt-get install -y libvips libvips-dev rustc

# Создание рабочей директории
WORKDIR /app

# Копирование Gemfile и Gemfile.lock и установка зависимостей Ruby через Bundler
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Копирование package.json и yarn.lock и установка зависимостей Node.js через Yarn
COPY package.json yarn.lock ./
RUN yarn install

# Копирование остальных файлов проекта
COPY . .

# Установка переменных окружения
ENV RAILS_ENV=development
ENV RUBYOPT=--yjit

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
