galaxy_info:
  author: Khomenok
  description: Start web site
  company: Innowise
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.1

  galaxy_tags: []
   
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
