---
- name: Create SSH user
  ansible.builtin.user:
    name: "{{ ssh_user }}"
    createhome: true
    home: "/home/{{ ssh_user }}"

- name: Create .ssh directory
  ansible.builtin.file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: "0700"

- name: Copy encrypted private key
  ansible.builtin.copy:
    src: "{{ ssh_key_path }}"
    dest: "/home/{{ ssh_user }}/.ssh/id_rsa"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: "0600"
