---
# tasks file for inodejs_npm
- name: Check if Node.js is installed
  command: node --version
  register: nodejs_version
  ignore_errors: true

- block:

  - name: Make Dir for Downloads
    shell: mkdir /home/ubuntu/downloads
    ignore_errors: true

  - name: Download Node.js binary
    get_url:
      url: "https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.xz"
      dest: "{{ download_folder }}/node-v18.17.1-linux-x64.tar.xz"

  - name: Extract Node.js binary
    unarchive:
      src: "{{ download_folder }}/node-v18.17.1-linux-x64.tar.xz"
      dest: "{{ download_folder }}/"
      owner: ubuntu
      mode: '0777'
      remote_src: true

#  - name: Copy directory
#    copy:
#      src: "{{ inodejs_npm_files }}/node-v18.17.1-linux-x64/"
#      dest: "/opt/nodejs/"
#      owner: ubuntu
#      group: ubuntu
#      mode: u+rwx,g+rwx,o+rwx
#      force: true
#      directory_mode: true
#      remote_src: no

#  - name: Copy directory
#    synchronize:
#      src: "{{ inodejs_npm_files }}/node-v18.17.1-linux-x64/"
#      dest: "/opt/nodejs/"
#      mode: "pull"

  - name: Add Node.js to PATH
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      line: 'export PATH=$PATH:/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin'
      create: yes
  
  - name: Create symlink to Node.js binary
    file:
      src: "/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin/node"
      dest: "/usr/sbin/node"
      state: link

  - name: Create symlink to npm binary
    file:
      src: "/home/ubuntu/downloads/node-v18.17.1-linux-x64/bin/npm"
      dest: "/usr/sbin/npm"
      state: link

  when: nodejs_version.rc == 127 or nodejs_version.rc != 0